### ISSUE TITLE
Compiling on Linux (Ubuntu 18.04 LTS)

### ISSUE THREAD

**Issue by magdesign** [pierrep/lpmt#1]
Thanks for keeping LPMT alive!
Just tried to compile on my Linux machine with OF_0.11.0 , but stuck on following error:

```
/opt/OF/libs/openFrameworks/events/ofEvent.h: In constructor ‘of::priv::StdFunctionId::StdFunctionId()’:
/opt/OF/libs/openFrameworks/events/ofEvent.h:54:7: error: expected unqualified-id before ‘=’ token
    id = nextId++;
       ^
```
Here to compiling log:

https://gist.github.com/magdesign/32bad3bcca4780ff2f9d6cdb522c5994

Any help welcome!

**Comment by pierrep** [comment]
Hi, I think that's a weird error caused by you including the ofxHotKeys_impl_mac.mm file. Delete it from the repo, and try again and report back. I need to find a way to get rid of it or make it conditionally compile. Probably I'll get rid of it, I don't like having objective c files floating around in there.

**Comment by magdesign** [comment]
removing ofxHotKeys_impl_mac.mm did fix the issue and I was able to compile LPMT,
thank you!

**Comment by pierrep** [comment]
So actually if you get the latest code from the repo, I've removed those files and condensed the same code into a header, which is fully cross-platform now. So next time you won't have this problem...it was bothering me too.
