### ISSUE TITLE
Install failed enofshape(true)

### ISSUE THREAD

**Issue by PM2000-maker** [pierrep/lpmt#10]
Hello,
During make I've this error : 
/of_v0.12.0_linux64gcc6_release/apps/myApps/lpmt/src/gui/Controls/ofxSimpleGuiQuadWarp.cpp:124:20: error: ‘TRUE’ was not declared in this scope
  124 |         ofEndShape(TRUE);
      |                    ^~~~
And make return error 1

Thanks for your job !

**Comment by pierrep** [comment]
Yeah that looks like a bug, probably surfacing due to the newer 0.12.0 libs. I'll take a look

**Comment by PM2000-maker** [comment]
Yes, I see after that you test LPMT with v0.11.2.
And it works with 0.11.2
